version: "3.3"

services:
  rmq:
    restart: always
    image: rabbitmq:management-alpine
    ports:
      - "15671-15672:15671-15672"

  mongo:
    restart: always
    build:
      dockerfile: MongoDB-Dockerfile
      context: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: root-user
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
      MONGO_INITDB_DATABASE: backend
    volumes:
      - ./db:/data/db

  server:
    build:
      dockerfile: Server-Dockerfile
      context: .
    restart: always
    depends_on:
      - rmq
      - mongo
    environment:
      - RABBIT_HOST=rmq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - SENTRY_DSN=https://475eb8f60aaf49edab8e8264fdf19b9b@o1164500.ingest.sentry.io/6312687
    ports:
      - "8000:8000"
    volumes:
      - ./instance/config.cfg:/opt/app/instance/config.cfg
      - ./sso/additional-info.json:/opt/app/sso/additional-info.json
      - ./sso/faculty-base-additional-info.json:/opt/app/sso/faculty-base-additional-info.json
      - ./sso/faculty_exchange_route.json:/opt/app/sso/faculty_exchange_route.json